// Auto-generated by Sumi — do not edit manually.
// Re-run `sumi dev` to refresh after adding or removing middleware.

declare global {
  type MiddlewareName = 'session-auth' | 'rate-limit' | 'deployer-auth';
}

export {};
